---
- name: Render StatsD config
  ansible.builtin.template:
    src: config.js.j2
    dest: "{{ statsd_install_dir }}/config.js"
    owner: "{{ statsd_user }}"
    group: "{{ statsd_group }}"
    mode: "0644"
  become: true
