---
- name: Install Node.js prerequisites
  ansible.builtin.include_tasks: nodejs.yaml

- name: Clone StatsD repository
  ansible.builtin.include_tasks: repo.yaml

- name: Configure StatsD
  ansible.builtin.include_tasks: config.yaml
