---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install Node.js and npm
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: present
  become: true
