---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Clone StatsD repository
  ansible.builtin.git:
    repo: "{{ statsd_repo }}"
    dest: "{{ statsd_install_dir }}"
    version: master
  become: true
