---
- name: Install Apache.
  hosts: centos
  become: true

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
  
          #  tasks:
    #    - name: Add an enviroment variable to the remote user's shell.
      #      lineinfile:
        #        dest: "~/.bash_profile"
          #        regexp: '^ENV_VAR='
          #        line: 'ENV_VAR=value'    
          #      become: false 
        # you can put 0 , no or false
      
        #    - name: Get the value of an enviroment variable.
      #      shell: 'source ~/.bash_profile && echo $ENV_VAR'
        #      register: foo

        #    - debug: msg=The variable is {{ foo.stdout }}

          #    - name: restart memcached
          #      service:
          #        name: memcached
          #        state: restarted

  tasks:
    - name: Ensure Apache is installed.
      yum:
        name: httpd
        state: present
    
    - name: Copy test config file.
      copy:
        src: /root/ansible/chapter3/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify:
        - restart apache
        
    
        #    - name: Make sure handlers are flushed immediately.
      #      meta: flush_handlers    

    - name: Ensure Apache is running and starts at boot.
      service:
        name: httpd
        state: started
        enabled: true      
     
  
