---
- name: Demo of ansible-lint-clean playbook.
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Get the system uptime.
      ansible.builtin.command: uptime
      register: system_uptime
      changed_when: false

    - name: Print the registered output of the 'uptime' command.
      ansible.builtin.debug:
        var: system_uptime.stdout
