---
- name: Install Apache
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name:
          - apache2
        state: present

    - name: Copy configuration file
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - src: apache2.conf
          dest: /etc/apache2/apache2.conf
