# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "geerlinggui/ubuntu:22.04"
  
 config.vm.provision "ansible" do |ansible|
   ansible.playbook = "playbook.yaml"
  end
end
