---
- name: Create a new folder under /root.
  hosts: all
  become: true
  tasks:
    - name: Create folder.
      ansible.builtin.file:
        path: /root/new
        state: directory
        mode: "0755"
        owner: root
        group: root
