---
- name: Apply distribution updates.
  hosts: all
  become: true
  pre_tasks:
    - name: Install updates on Ubuntu.
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Provision web servers and edit homepage.
  hosts: web_servers
  become: true
  handlers:
    - name: Restart Apache.
      tags: apache,apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
  tasks:
    - name: Install apache2 and php packages.
      tags: apache,apache2,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Edit line in file.
      tags: apache,apache2
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        regexp: '^Welcome to My'
        line: Welcome to my new servers
      notify: Restart Apache.

- name: Provision database servers.
  hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb.
      tags: db,mariadb,ubuntu
      ansible.builtin.apt:
        name: mariadb-server
        state: present
      when: ansible_distribution == "Ubuntu"

- name: Provision file servers.
  hosts: file_servers
  become: true
  tasks:
    - name: Install samba package.
      tags: samba
      ansible.builtin.apt:
        name: samba
        state: present
