---
- name: Install Apache and PHP.
  hosts: all
  become: true
  tasks:
    - name: Install apache2 and php packages.
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"
