---
- name: Remove Apache and PHP.
  hosts: all
  become: true
  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true

    - name: Remove apache2 and php packages.
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
