---

- hosts: all
  pre_tasks:

  - name: install updates Ubuntu 
    tags: always
    apt:  
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  tasks: 

  - name: create user 
    tags: always
    user:
      name: nikolay
      groups: root

  - name: add ssh key 
    tags: always
    authorized_key:
      user: nikolay
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpkQlYB6CA1GcJCS0wI/WrHdV9hY8mhYLD86b4pA0KFzYrMIL0WHza0HtsrujzL7iJhrDf6bYQhOWkd+zviQDM0uFPbzkZpXyPDRIt0tnP5usBCMvrVkjZSmw5ZhUE/7bsu2PxMvLCf7TrJrykVjiwJIuRhXawTEJUBryW5MfgQFR/uhqhjcrzHmLf68DDOXtaSUR7g9lJD4N//ilanK1c+RQWUiRoULIxeS4ZaCSTuTQ9n313EQT1AL4iElwZNoaiiVzIKSTsf//zuVbRma2th91kw5F8IsnedH5L+bOAHisprG/EpaZ0NKQYLssi1hI4Pes/Y8ah5BgVcRj/hMvqkiWswKiTVsznDEBpdZ1ekY7C4uubvGQP33KmopaRHiIY5ZYHg4aMcq8pzNm9E573uSmtjc8y6ePeDMq4ie4EW6TStJJE7ZPBpqcrxR6fx6Fwj+MGskACtsbt7/tzVC3n2BulOeGM2PnCTdSHTjt2QGdiB5pLE+pBT1koKIweZyM= root@ansible"

  - name: add sudo users file
    tags: always
    copy:
      src: /etc/ansible/sudoer_nikolay
      dest: /etc/sudoers.d/nikolay
      owner: root
      group: root
      mode: 0440


- hosts: web_servers
  tasks:

   - name: install apache2 and php packages
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"  




- hosts: db_servers
  tasks:

   - name: install mariadb
     tags: db,mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
    

    
    
- hosts: file_servers
  tasks:

  - name: install samba package
    tags: samba
    apt:
      name: samba
      state: latest

