- name: install apache2 and php packages
  tags: apache,apache2,ubuntu
  apt:
    name:
       - apache2
       - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu" 


  #- name: edit line in file
  # tags: apache,apache2
  # lineinfile:
  # path: /var/www/html/index.html
  # regexp: '^Welcome to My'
  # line: Welcome to my new servers
  #register: apache2

  #- name: restart apache
  #tags: apache,apache2
  #service:
  #name: apache2
  #state: restarted
  #when: apache2.changed

- name: copy html file for site
  tags: apache,apache,apache2,httpd
  copy:
    src: /etc/ansible/roles/web_servers/files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
