- name: Install ca-certificates, curl, and GnuPG
  apt:
    name: ['ca-certificates', 'curl', 'gnupg']
    state: present
    with_items:
     - ca-certificates
     - curl
     - gnupg

- name: Create a dir
  file:
     path: /etc/apt/keyrings
     state: directory
     owner: ansible
     group: ansible
     mode: "0755"

- name: Run comand RAW
  raw: |
    curl -fsSl  https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    NODE_MAJOR=20
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

