---
- name: Deploy a Node.js app behind Forever.
  hosts: all
  become: true

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Ensure firewalld is stopped (since this is a test server).
      ansible.builtin.service:
        name: firewalld
        state: stopped

    - name: Install Node.js and npm.
      ansible.builtin.dnf:
        name: npm
        state: present
        enablerepo: epel

    - name: Install Forever (to run our Node.js app).
      community.general.npm:
        name: forever
        global: true
        state: present

    - name: Ensure Node.js app folder exists.
      ansible.builtin.file:
        path: "{{ node_apps_location }}"
        state: directory
        mode: "0755"

    - name: Copy example Node.js app to server.
      ansible.builtin.copy:
        src: app
        dest: "{{ node_apps_location }}"
        mode: "0755"

    - name: Install app dependencies defined in package.json.
      community.general.npm:
        path: "{{ node_apps_location }}/app"

    - name: Check list of running Node.js apps.
      ansible.builtin.command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app.
      ansible.builtin.command: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"
      changed_when: true
