---
- name: Add ssh key for nikolay.
  ansible.posix.authorized_key:
    user: nikolay
    key: "{{ nikolay_ssh_key | default('') }}"
    state: present
  when: (nikolay_ssh_key | default('')) | length > 0
