---
galaxy_info:
  author: Nikolay Dimitrov
  description: An Ansible role to install StatsD
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy

dependencies: []
