---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: [git, curl, software-properties-common]
    state: present
  become: yes

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Download Node.js setup script
  get_url:
    url: "{{nodejs_url}}"
    dest: /tmp/nodesource_setup.sh

- name: Run Node.js setup script
  command: sudo bash /tmp/nodesource_setup.sh
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  become: yes

- name: Install Node.js
  apt:
    name: [nodejs]
    state: present
  become: yes      

- name: Clone Uptime Kuma repository
  git:
    repo: "{{uptime_kuma_repo}}"
    dest: /opt/uptime-kuma
    version: "{{uptime_kuma_version}}"
  become: yes

- name: Install pm2
  command: npm install pm2@latest -g
  become: yes

- name: Install Uptime Kuma dependencies
  command: npm install
  args:
    chdir: /opt/uptime-kuma
  become: yes

- name: Build Uptime Kuma
  command: npm run setup
  args:
    chdir: /opt/uptime-kuma
  become: yes

- name: Start Uptime Kuma
  command: pm2 start server/server.js --name uptime-kuma
  args:
    chdir: /opt/uptime-kuma
  become: yes

  - name: "Install nginx"
  include_tasks: nginx.yaml

