- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install the prerequisite packages
  apt:
    name: ["software-properties-common", "apt-transport-https"]
    update_cache: yes
  become: yes
