- name: Create promtail user and group
  include_tasks: prerequisites.yaml

- name: Install required packages and dir
  include_tasks: required.yaml

- name: Download promtail binary
  get_url:
    url: "{{promtail_binary_file}}"
    dest: "{{promtail_installation}}"
  become: yes  

- name: Unzip promtail binary
  unarchive:
    src: "{{promtail_installation}}/{{promtail_binary_file | basename }}"
    dest: "{{promtail_installation}}"
    remote_src: yes
  become: yes  

- name: Setup promtail config
  template:
    src: promtail-config.yaml.j2
    dest: "{{promtail_config_path}}/{{promtail_config_name}}"
    owner: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
  become: yes  

- name: Setup promtail systemd
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
  become: yes

- name: Restart promtail
  systemd:
    name: promtail
    enabled: true
    daemon_reload: true
    state: restarted
  become: yes

- name: Move promtail zip file to /tmp
  command: mv "{{promtail_installation}}/{{promtail_binary_file | basename }}" /tmp/
  become: yes