- name: Create promtail group
  group:
    name: "{{promtail_group}}"
    system: true
    state: present
  become: yes

- name: Create promtail user
  user:
    name: "{{promtail_user}}"
    group: "{{promtail_group}}"
    system: true
    state: present
  become: yes