---
- name: Apply distribution updates.
  hosts: all
  become: true
  pre_tasks:
    - name: Update repository index (Ubuntu).
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- name: Apply web_servers role.
  hosts: web_servers
  become: true
  roles:
    - web_servers
