- name: Create Loki group
  group:
    name: "{{loki_group}}"
    system: true
    state: present
  become: yes

- name: Create Loki user
  user:
    name: "{{loki_user}}"
    group: "{{loki_group}}"
    system: true
    state: present
  become: yes