---
- name: Restart Uptime Kuma
  ansible.builtin.systemd:
    name: uptime-kuma
    daemon_reload: true
    state: restarted
  become: true

- name: Test Nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  become: true
  listen: Validate and reload Nginx

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
  listen: Validate and reload Nginx
