---

- name: install web server packages
  tags: apache,apache2,ubuntu
  become: true
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: present

- name: edit apache web server
  tags: apache,apache2
  lineinfile:
    path: /var/www/html/index.html
    regexp: '^<p>This is'
    line: <p>This is the NEW homepage for my website!!!</p>
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache
