---
- name: Install Uptime Kuma
  hosts: cluster1
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install required packages
      apt:
        name: [git, curl, software-properties-common]
        state: present
      become: yes

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Download NodeSource setup script
      get_url:
        url: https://deb.nodesource.com/setup_16.x
        dest: /tmp/nodesource_setup.sh

    - name: Run NodeSource setup script
      command: sudo bash /tmp/nodesource_setup.sh
      args:
        creates: /etc/apt/sources.list.d/nodesource.list
      become: yes

    - name: Install Node.js
      apt:
        name: [nodejs]
        state: present
      become: yes      

    - name: Clone Uptime Kuma repository
      git:
        repo: https://github.com/louislam/uptime-kuma.git
        dest: /opt/uptime-kuma
        version: 1.21.3
      become: yes

    - name: Install pm2
      command: npm install pm2@latest -g
      become: yes

    - name: Install Uptime Kuma dependencies
      command: npm install
      args:
        chdir: /opt/uptime-kuma
      become: yes

    - name: Build Uptime Kuma
      command: npm run setup
      args:
        chdir: /opt/uptime-kuma
      become: yes

    - name: Start Uptime Kuma
      command: pm2 start server/server.js --name uptime-kuma
      args:
        chdir: /opt/uptime-kuma
      become: yes

