---
- name: Add ssh key for nikolay.
  ansible.posix.authorized_key:
    user: nikolay
    key: "{{ nikolay_ssh_key | default('') }}"
    state: present
  when: (nikolay_ssh_key | default('')) | length > 0

- name: Configure sshd from template.
  tags: ssh
  ansible.builtin.template:
    src: sshd_config_ubuntu.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart sshd.
