---
- name: Demo of include_tasks and ansible-playbook --syntax-check.
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Include task file conditionally at runtime.
      ansible.builtin.include_tasks: dates.yml

    - name: Print a debug message.
      ansible.builtin.debug:
        msg: "Hello there."
