- name: Install required packages and dir
  include_tasks: prerequisites.yaml

- name: Install required packages and dir
  include_tasks: required.yaml

- name: Download Loki binary
  get_url:
    url: "{{loki_binary_file}}"
    dest: "{{loki_installation}}"
  become: yes  

- name: Unzip Loki binary
  unarchive:
    src: "{{loki_installation}}/{{loki_binary_file | basename }}"
    dest: "{{loki_installation}}"
    remote_src: yes
  become: yes  

- name: Setup loki config
  template:
    src: loki-config.yaml.j2
    dest: "{{loki_config_path}}/{{loki_config_name}}"
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
  become: yes  

- name: Setup Loki systemd
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
  become: yes

- name: Restart Loki
  systemd:
    name: loki
    enabled: true
    daemon_reload: true
    state: restarted
  become: yes
