- name: Create loki group
  group:
    name: "{{ loki_group }}"
    system: true
    state: present
  become: yes

- name: "Create loki user"
  user:
    name: "{{ loki_user }}"
    group: "{{ loki_group }}"
    system: true
    state: present
  become: yes

- name: Install required packages and dir
  include_tasks: required.yaml

- name: Download Loki binary
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.7.0/loki-linux-amd64.zip
    dest: /opt/loki

- name: Unzip Loki binary
  unarchive:
    src: /opt/loki/loki-linux-amd64.zip
    dest: /opt/loki
    remote_src: yes

- name: Setup loki config
  template:
    src: loki-config.yaml.j2
    dest: /etc/loki/loki-config.yaml
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"

- name: Setup Loki systemd
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
  become: yes

- name: Restart Loki
  systemd:
    name: loki
    enabled: true
    daemon_reload: true
    state: restarted
  become: yes
