---
- name: Install Loki and configure
  hosts: your_target_hosts
  become: yes  # Ensure you have the necessary privileges to install packages and create directories

  tasks:
    - name: Install unzip package
      apt:
        name: unzip
        state: present

    - name: Create /etc/loki directory
      file:
        path: /etc/loki
        state: directory

    - name: Download Loki binary
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.7.0/loki-linux-amd64.zip
        dest: /usr/bin/loki-linux-amd64.zip

    - name: Unzip Loki binary
      unarchive:
        src: /usr/bin/loki-linux-amd64.zip
        dest: /usr/bin/
        remote_src: yes
