- name: Install unzip package
  apt:
    name: unzip
    state: present

- name: Create /etc/loki directory
  file:
    path: /etc/loki
    state: directory

- name: Create /usr/local/bin directory
  file:
    path: /usr/local/bin
    state: directory

- name: Download Loki binary
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.7.0/loki-linux-amd64.zip
    dest: /usr/local/bin/loki-linux-amd64.zip

- name: Unzip Loki binary
  unarchive:
    src: /usr/local/bin/loki-linux-amd64.zip
    dest: /usr/local/bin
    remote_src: yes
