- name: Update apt cache
  apt:
    update_cache: yes

- name: Install unzip package
  apt:
    name: [ "zip", "unzip" ]
    state: present

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
    mode: '0700'
  loop:
    - "{{loki_installation}}"
    - "{{loki_config_path}}"
  become: yes