- name: Install unzip package
  apt:
    name: unzip
    state: present

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
    mode: '0700'
  loop:
    - /opt/loki
    - /etc/loki
  become: yes